"""
Utility functions for performing Unix/Linux commands.

The following functions are implemented:

    - cut_cmd
    - awk_cmd
"""

import logging
import sys
import re
from pathlib import Path
import subprocess as sp

from typing import Callable, Any, List
from gcmpy.utils.logger_ops import logger_setup

logger = logger_setup(filename=__name__,
                      file_handler=True,
                      file_level=logging.ERROR,
                      stream_handler=False)

def exec_cmd(cmd: list, **kwargs: dict) -> tuple[str | None, str | None, int]:
    """
    Execute a command

    Parameters
    ----------
    cmd : list[str] | str
        command to execute
    kwargs : dict
        flags

    Returns
    -------
    output, error, return_code : tuple[str | None, str | None, int]
        output, error(s), and return code generated by command
    """
    p = sp.Popen(cmd, **kwargs)
    p.wait()
    return_code = p.returncode
    output, error = p.communicate()
    if error:
        error = error.decode()
        logger.error(error)
    if output:
        output = output.decode()
    logger.debug('exec_cmd: DONE')

    return output, error, return_code

def pipe_cmd(cmd: list[str], outfile: str) -> None:
    """
    Run the command and pipe the output into a file.

    Parameters
    ----------
    cmd : list[str]
        The command to be executed as comma-delimited list of strings
    outfile : str
        File name

    """
    with open(outfile, "w") as fh:
        run = sp.Popen(cmd, stdout=fh)
    return_code = run.wait()
    if return_code != 0:
        raise Exception(f'Execution failed with {cmd}')

def cut_cmd(text: str, 
            delimiter: str = '\t', 
            fields: List[int] = None) -> str:
    """
    Mimics the Unix 'cut' command on a string:

        cut -d <delimiter> -f <fields>

    Extracts specified fields from each line based on a delimiter.

    Note:
       1. 1-Based Indexing: Just like the real Unix cut command, 
          this function expects field numbers starting at 1 
          (e.g., fields=[1, 3]), and internally converts them 
          to Python's 0-based indices.
       2. Missing Delimiters: In standard Unix behavior, 
          if a line does not contain the delimiter at all, 
          cut simply prints the entire unmodified line. 
          This function replicates that logic.
       3. Out of Bounds: If you ask for a field that doesn't 
          exist on a particular line (e.g., field 5 on a line 
          with only 3 parts), it simply ignores it, 
          preventing IndexError crashes.

    Parameters
    ----------
    text : str
        The multi-line input string to process.
    delimiter : str
        The character that separates fields (default is Tab).
    fields : List[int]
        A list of field numbers to extract (1-based index, like Unix).
        Defaults to [1] if not provided.

    Returns
    -------
    cut_str : str
        A string containing the extracted fields.
    """
    if fields is None:
        fields = [1]

    result_lines = list()

    for line in text.splitlines():
        # Unix cut returns the whole line if the delimiter isn't found
        if delimiter not in line:
            result_lines.append(line)
            continue

        # Split the line into parts
        parts = line.split(delimiter)

        extracted = []
        for f in fields:
            # Unix fields are 1-based, so subtract 1 for Python's 0-based indexing
            idx = f - 1
            if 0 <= idx < len(parts):
                extracted.append(parts[idx])

        # Join the extracted fields back together with the delimiter
        result_lines.append(delimiter.join(extracted))

    return "\n".join(result_lines)

def awk_cmd(text: str, 
            action: Callable[[int, int, list], Any], 
            delimiter: str = None) -> str:
    """
    Mimics the core data-extraction behavior of the Unix 'awk' command.
    The implementation of:
       awk '{print $1, $12}'
    is:
       awk_cmd(data, lambda NR, NF, F: f"{F[1]} {F[12]}")

    Note:
      1. The F Array (Fields): In awk, $0 is the whole line, 
         $1 is the first column, $2 is the second column. 
         Here, we use a Python list F, so F[0] is the whole line, 
         F[1] is the first column, etc.
      2. NR and NF: Just like standard awk variables, 
         NR gives you the current line number, and NF tells you 
         how many fields are on that line.
      3. The Callback: Instead of an awk syntax string, you pass 
         a Python lambda or function. If the function returns a string, 
         it is printed. If it returns None, it skips the line 
         (which perfectly replicates awk filtering).

    Parameters
    ----------
    text : str
        The multi-line input string to process.
    action :  
        A function/lambda applied to each line. It must accept three arguments:
          - NR (int): The current Record Number (line number, 1-based).
          - NF (int): The Number of Fields in the current line.
          - F (list): The fields. F[0] is the whole line ($0).
                      F[1] is the first field ($1), F[2] is the second ($2), etc.
          If the action returns a value (not None), it gets added to the output.
    delimiter : str
        The field separator. Defaults to None (splits on any whitespace, like awk).

    Returns:
        A string containing the joined results of the action.
    """
    results = list()

    for nr, line in enumerate(text.splitlines(), start=1):
        # Split the line into parts based on the delimiter
        parts = line.split(delimiter)
        nf = len(parts)

        # Create a list where index 0 is the whole line (like $0 in awk),
        # and index 1 is the first field (like $1 in awk).
        # We append empty strings to prevent IndexError if a line is too short.
        f = [line] + parts + [""] * 100

        try:
            # Execute the user-provided action
            output = action(nr, nf, f)

            # If the action returned something, keep it
            if output is not None:
                results.append(str(output))
        except Exception as e:
            results.append(f"Error on line {nr}: {e}")

    return "\n".join(results)

